title = "Sparkle Simulator"
author = "Krishna BM"
shortname = "sparklesimulator"
version = "1.0.0"
support_email = "krishnabmahadevan@gmail.com"
copyright_message = "Copyright © 2023 KBM."
icon = "src/assets/icon.png"
